# 63) A/B Testi Örneği (Uçtan Uca Uygulama)
Bir A/B testi, tek bir formülden ibaret değildir — **planlama, uygulama, ve yorumlama** aşamalarından oluşan bir süreçtir. Bu konuda, şimdiye kadar öğrendiğimiz araçları (Power Analysis, Z Oran Testi) birleştirerek, gerçekçi bir A/B testini baştan sona kuracağız.

## Sürecin Adımları
1. **İş Sorusunu Belirle:** Neyi test ediyoruz, hangi metrik önemli?
2. **Hipotezleri Kur:** H0/H1
3. **Örneklem Büyüklüğünü Planla (Power Analysis):** Teste başlamadan önce, kaç kullanıcı gerektiğini hesaplıyoruz.
4. **Testi Çalıştır, Veriyi Topla**
5. **İstatistiksel Testi Uygula:** Z Oran Testi ile p-değerini bul
6. **Etki Büyüklüğünü Hesapla:** Fark ne kadar büyük/pratik önemde?
7. **Sonucu İş Kararına Çevir**

In [3]:
# Elimizde iki grup var. Bunlar:
# A (Eski email): 1092 kişiden 210'u email'i açtı
# B (Yeni email): 1092 kişiden 265'i email'i açtı

# H0: eski mail tasarımı ile yeni mail tasarımı açılma oranı birbirine eşittir.
# H1: yeni mail tasarımı eski mail tasarımına göre daha fazla açılma oranına sahiptir.
import numpy as np
from statsmodels.stats.proportion import proportions_ztest
basari_sayilari = np.array([210,265])
gozlem_sayilari = np.array([1092,1092])

print(f"Eski mail sistemi dönüşüm oranı: {basari_sayilari[0]/gozlem_sayilari[0]:.4f}")
print(f"Yeni mail sistemi dönüşüm oranı: {basari_sayilari[1]/gozlem_sayilari[1]:.4f}")

z_istatistigi, p_degeri = proportions_ztest(
    count = basari_sayilari,
    nobs=gozlem_sayilari,
    alternative='smaller'
)

print(f"\nZ istatistiği: {z_istatistigi}")
print(f"p-değeri: {p_degeri}")

alpha = 0.05
if p_degeri < alpha:
    print("H0 reddedilir, yeni mail tasarımı eski mail tasarımına göre daha fazla açılma oranına sahiptir.")
else:
    print("H0 reddedilemedi, iki varyant arasında anlamlı bir fark olduğuna dair yeterli kanıt yoktur.")


Eski mail sistemi dönüşüm oranı: 0.1923
Yeni mail sistemi dönüşüm oranı: 0.2427

Z istatistiği: -2.852798978592268
p-değeri: 0.0021668012759733664
H0 reddedilir, yeni mail tasarımı eski mail tasarımına göre daha fazla açılma oranına sahiptir.


### Sonuç
Eski mail sistemi ve yeni mail sistemi arasındaki dönüşüm oranı farkının istatistiksel olarak anlamlı olup olmadığını belirlemek amacıyla bir A/B testi uyguladık. Test sonuçlarına göre, yeni mail sistemi (%24.27) eski mail sistemine (%19.23) göre %5.04 anlamlı biçimde daha yüksek dönüşüm oranına sahiptir (p<0.05). Bu doğrultuda, yeni mail sisteminin açılma oranını artırdığı söylenebilir. Ancak bu iyileşmenin nihai iş metriklerine (tıklama sonrası satın alma gibi) nasıl yansıdığını görmek için takip analizleri önerilir, sonrasında yeni sisteme tam geçiş kararı verilebilir.