# 38) Poisson Dağılımı
Poisson Dağılımı, belirli bir **zaman aralığında** veya **alanda**, ortalama gerçekleşme sıklığı bilinen bir olayın **kaç kere** gerçekleşeceğini modelleyen kesikli bir olasılık dağılımıdır.

## Binom'dan Temel Farkı
Binom dağılımında sabit bir **deneme sayısı (n)** vardı ("10 kere para at, kaçı yazı gelir"). Poisson'da ise böyle bir "deneme sayısı" **yoktur** bunun yerine sadece bir **oran/yoğunluk (λ, lambda)** vardır: "bir saatte ortalama kaç müşteri gelir", "bir günde ortalama kaç arıza olur" gibi. Teorik olarak olay, o zaman aralığında **sonsuz kere** gerçekleşebilir (çok nadir olsa da), bu yüzden Binom'daki gibi "en fazla n kere" sınırı yoktur.

## Parametre
Poisson'un tek bir parametresi vardır:
- **λ (lambda):** Belirli bir aralıktaki **ortalama** gerçekleşme sayısı

## Olasılık Kütle Fonksiyonu (PMF)
$$P(X=k) = \frac{\lambda^k e^{-\lambda}}{k!}$$

Burada $k$, o aralıkta gerçekleşmesini merak ettiğimiz olay sayısı, $e$ ise doğal logaritma tabanı (≈2.71828), sabit bir matematik sabiti.

## Beklenen Değer ve Varyans
$$E(X) = \lambda \qquad Var(X) = \lambda$$

İlginç bir özellik: Poisson dağılımında **beklenen değer ile varyans birbirine eşittir** bu özellik, Poisson'u diğer dağılımlardan ayıran kendine özgü bir özelliktir..

## Kullanım Koşulları (Ne Zaman Poisson Kullanılır?)
1. Olaylar birbirinden **bağımsız** gerçekleşmeli
2. Belirli bir zaman/alan aralığındaki **ortalama** oran (λ) sabit ve biliniyor olmalı
3. İki olay **aynı anda** gerçekleşemez (yeterince küçük bir zaman diliminde)

## Kullanım Alanları
- Bir çağrı merkezine bir saatte gelen çağrı sayısı
- Bir web sitesine bir dakikada gelen ziyaretçi sayısı
- Bir mağazaya bir günde gelen iade sayısı
- Bir üretim hattında bir günde çıkan hatalı ürün sayısı

## Binom ile Bağlantı (İleri Seviye Not)
Aslında Poisson, Binom dağılımının özel bir **limit hali** olarak da düşünülebilir: n (deneme sayısı) çok büyük, p (başarı olasılığı) çok küçükken, Binom dağılımı Poisson dağılımına yakınsar. Bu yüzden "çok sayıda potansiyel fırsat var ama her birinin gerçekleşme olasılığı çok düşük" senaryolarında (örn: bir günde milyonlarca insan var ama sadece birkaçı mağazana giriyor) Poisson tercih edilir.

In [2]:
from scipy import stats

# --- Örnek 1: Mağaza İadeleri ---
lambda_iade = 4  # Saatte ortalama 4 iade
k_iade = 6        # 6 iade gelme olasılığını soruyoruz

olasilik_iade = stats.poisson.pmf(k=k_iade, mu=lambda_iade)
print(f"Saatte ortalama {lambda_iade} iade olan mağazada, 1 saatte tam {k_iade} iade gelme olasılığı: {olasilik_iade:.4f}")

# --- Örnek 2: Ekmek Satışı ---
lambda_ekmek = 50  # 7-8 arası ortalama 50 ekmek
k_ekmek = 65        # 65 ekmek satma olasılığını soruyoruz

olasilik_ekmek = stats.poisson.pmf(k=k_ekmek, mu=lambda_ekmek)
print(f"Saatte ortalama {lambda_ekmek} ekmek satan fırında, {k_ekmek} ekmek satma olasılığı: {olasilik_ekmek:.4f}")

# 65 veya daha fazla ekmek satma olasılığı (kümülatif, CDF'nin tersi)
olasilik_65_ustu = 1 - stats.poisson.cdf(k=64, mu=lambda_ekmek)
print(f"Bu fırının 65 veya daha fazla ekmek satma olasılığı: {olasilik_65_ustu:.4f}")

Saatte ortalama 4 iade olan mağazada, 1 saatte tam 6 iade gelme olasılığı: 0.1042
Saatte ortalama 50 ekmek satan fırında, 65 ekmek satma olasılığı: 0.0063
Bu fırının 65 veya daha fazla ekmek satma olasılığı: 0.0236


### Sonuç
Yukarıda saatte ortalama 4 adet ürünü iade alan bir mağazaya, saatte ortalama 6 adet ürünün gelme olasılığı %10.42 bu durumda bu iade olasılığına karşılık ürün veya müşteri bazlı sorunların tespit edilip iade oranlarının düşürülmesi sağlanmalıdır. Öte yandan sabah 7-8 arası ortalama 50 ekmek satan bir fırının, bu saat aralığında en az 65 ekmek satma olasılığı %2.36 bu durumda benim önerim bu kadar düşük bir olasılık için üretim kapasitesinin değiştirilmemesi yönündedir. 